# Set theme
remote_theme: daviddarnes/alembic

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji
- jekyll-remote-theme
- jekyll-gist
- jekyll-twitter-plugin

# Site settings
url: 'https://mydomain.com'
baseurl: ''
title: 'Berkeley Psychology Graduate Blog'
description: 'Berkeley Psychology Graduate Blog'
permalink: pretty
logo: "https://upload.wikimedia.org/wikipedia/commons/7/74/Greek_uc_psi.svg"
email: "maedbhking@berkeley.edu"

# Pagination
paginate: 5
paginate_path: spotlights/page:num

# Header nav
navigation_header:
- title: News
  url: /
- title: About
  url: /about/
- title: Spotlights
  url: /spotlights/
# - title: Outreach
#   url: /outreach/
- title: Contact
  url: /contact/

# Footer nav
navigation_footer:
- title: Back to top
  url: "#top"

# Collections
collections:
  posts:
    title: Shining a Light on Graduate Student Research
    output: true
    description: "Each month we 'spotlight' the work of graduate students across all areas of psychology: 
    cognitive and behavioural neuroscience, social-personality, cognition, and development."
    feature_text: |
      <font color="white" size="8pt">Graduate Student Spotlights</font>
    feature_image: "/images/Blog_Spotlights_Cover.jpg"
